
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  zipkin:
    baseUrl: http://zipkin-svc:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-15585796.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa7ytgmx633WC1mX5d7
            client-secret: IEOpwAvKPWWJeKicZ_2Fh3nURsiKQxRYjCPInguA
        provider:
          okta:
            issuer-uri: https://dev-12188475.okta.com/oauth2/default

okta:
  oauth2:
    issuer:  https://dev-12188475.okta.com/oauth2/default
    audience: api://default




resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
#  zipkin:
#    baseUrl: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0
#    base-url=http://localhost:9411/
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}